export * as Myself from './Myself';
export { default as ForgotPage } from './components/pages/Forgot';
export type { ForgotProps as ForgotPageProps } from './components/pages/Forgot';
export { default as SetupPage } from './components/pages/Setup';
export type { SetupProps as SetupPageProps } from './components/pages/Setup';
export { default as UsersPage } from './components/pages/Users';
export type { UsersProps as UsersPageProps } from './components/pages/Users';
export { default as VerificationPage } from './components/pages/Verification';
export type { VerificationProps as VerificationPageProps } from './components/pages/Verification';
export { default as AccountDialog } from './components/dialogs/Account';
export type { AccountProps as AccountDialogProps } from './components/dialogs/Account';
export { default as SignInDialog } from './components/dialogs/SignIn';
export type { SignInProps as SignInDialogProps } from './components/dialogs/SignIn';
export declare const RIGHTS: {
    CREATE: number;
    READ: number;
    UPDATE: number;
    DELETE: number;
    ALL: number;
};
